name: device_preview
version: 0.7.1
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  device_frame: ^0.4.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.1
  http: ^0.12.0+2
  json_annotation: ^4.0.1
  path: ^1.8.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^1.5.0
  build_runner: 
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
